# AES-256-CBC requires a 32-byte key and 16 byte iv

# remove iv if a random generated iv is desired

development:
  cipher: AES-256-CBC
  key: basho123456789101112basho_dev123
  iv: !binary |
    ABYLnUHWE/fIwE2gKYC6hg==

test:
  cipher: AES-256-CBC
  key: basho123456789101112basho_dev123
  iv: !binary |
    ABYLnUHWE/fIwE2gKYC6hg==

test-without-iv:
  cipher: AES-256-CBC
  key: basho123456789101112basho_dev123

prod:
  cipher: AES-256-CBC
  key: example123456789101112basho_prod
  base64: true
